[package]
name = "worn"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.36", features = ["derive"] }
nom = "7.1.3"
nom_locate = "4.2.0"

[dev-dependencies]
insta = "1.42.2"
