name: CI and Release

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            extension: ""
          - os: macos-latest
            extension: ""
          - os: windows-latest
            extension: ".exe"

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Building worn on ${{ matrix.os }}
        run: |
          cargo build --release
          ./target/release/worn${{ matrix.extension }} -h

      - name: Release ${{ matrix.os }}
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref }}
          file: "target/release/worn${{ matrix.extension }}"
          asset_name: "worn-${{ github.ref_name }}-${{ matrix.os }}${{ matrix.extension }}"
          overwrite: true
